name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with black
      run: |
        pip install black
        # stop the build if there are Python syntax errors
        black ./whatis --check
    - name: Check type errors with mypy
      run: |
        pip install mypy
        # stop the build if there are Python type errors
        mypy ./whatis/
    - name: Test with pytest
      run: |
        pip install pytest
        pytest 
