name: Whatis publish

on:
    tag:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
        python-version: 3.6
        python-version: 3.5
    - name: Create distributions
      run: |
        python setup.py sdist bdist_wheel
      env:
        PYTHONPATH: /whatis/
    - name: Create distributions
      run: |
        pip install twine
        twine upload dist/*
      env:
        TWINE_USERNAME: $TWINE_USERNAME
        TWINE_PASSWORD: $TWINE_PASSWORD
